Extension { #name : #SoilClusterRecord }

{ #category : #'*Soil-Core-Tests' }
SoilClusterRecord >> setBehaviorDescriptions: aCollection [ 
	behaviorDescriptions := aCollection
]

{ #category : #'*Soil-Core-Tests' }
SoilClusterRecord >> setBytes: aCollection [ 
	bytes := aCollection 
]

{ #category : #'*Soil-Core-Tests' }
SoilClusterRecord >> setReferences: aCollection [ 
	references := aCollection
]
