Class {
	#name : 'SoilTestClass1',
	#superclass : 'Object',
	#instVars : [
		'one',
		'two',
		'three'
	],
	#category : 'Soil-Core-Tests',
	#package : 'Soil-Core-Tests'
}

{ #category : 'accessing' }
SoilTestClass1 >> one [

	^ one
]

{ #category : 'accessing' }
SoilTestClass1 >> one: anObject [

	one := anObject
]

{ #category : 'accessing' }
SoilTestClass1 >> three [

	^ three
]

{ #category : 'accessing' }
SoilTestClass1 >> three: anObject [

	three := anObject
]

{ #category : 'accessing' }
SoilTestClass1 >> two [

	^ two
]

{ #category : 'accessing' }
SoilTestClass1 >> two: anObject [

	two := anObject
]
