Class {
	#name : #SoilRecursiveHashTestObject,
	#superclass : #Object,
	#instVars : [
		'one',
		'two',
		'three',
		'four',
		'five',
		'six'
	],
	#category : #'Soil-Core-Tests-TestData'
}

{ #category : #accessing }
SoilRecursiveHashTestObject >> five [

	^ five
]

{ #category : #accessing }
SoilRecursiveHashTestObject >> five: anObject [

	five := anObject
]

{ #category : #accessing }
SoilRecursiveHashTestObject >> four [

	^ four
]

{ #category : #accessing }
SoilRecursiveHashTestObject >> four: anObject [

	four := anObject
]

{ #category : #accessing }
SoilRecursiveHashTestObject >> one [

	^ one
]

{ #category : #accessing }
SoilRecursiveHashTestObject >> one: anObject [

	one := anObject
]

{ #category : #accessing }
SoilRecursiveHashTestObject >> six [

	^ six
]

{ #category : #accessing }
SoilRecursiveHashTestObject >> six: anObject [

	six := anObject
]

{ #category : #accessing }
SoilRecursiveHashTestObject >> three [

	^ three
]

{ #category : #accessing }
SoilRecursiveHashTestObject >> three: anObject [

	three := anObject
]

{ #category : #accessing }
SoilRecursiveHashTestObject >> two [

	^ two
]

{ #category : #accessing }
SoilRecursiveHashTestObject >> two: anObject [

	two := anObject
]
