"
This class implements the SoilIndexDictionary that uses a Lined List as an index.

See the superclass for more informaion about indexed dictionaries

"
Class {
	#name : #SoilSkipListDictionary,
	#superclass : #SoilIndexedDictionary,
	#category : #'Soil-Core-Index-SkipList'
}

{ #category : #rewriting }
SoilSkipListDictionary >> compact [ 
	index wrapped compact
]

{ #category : #initialization }
SoilSkipListDictionary >> createIndex [ 
	^ SoilSkipList new
		initializeHeaderPage;
		valueSize: 8;
		yourself
]

{ #category : #rewriting }
SoilSkipListDictionary >> rewriteUsing: aBlock [
	index wrapped rewriteUsing: aBlock
]
